language: dart
env:
  global:
    # COVERALLS_TOKEN
    secure: aTnwsQmp/ngr1eXNVULJekdHhgvQq3PomunMOqeqA+5OY1MpSrdQgMigjT/VdjaMFe6mackHCR7sIhWcsiT2weZItVkeOYckT41ICrogP7bau7GgpcCjntHZ0byYN8MImbo/zJPZG3sh2iZwL2YFx+TjjHHkAbn7RovKeAmhMIM=
dart:
- stable
- dev
after_success:
- pub global activate dart_coveralls
- pub global run dart_coveralls:dart_coveralls report --token $COVERALLS_TOKEN ./test/all_tests.dart

